/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: swig\sxtwl.i

package sxtwl

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef int intgo;
typedef unsigned int uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


extern void _wrap_Swig_free_sxtwl_36456a96f054a683(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_sxtwl_36456a96f054a683(swig_intgo arg1);
extern void _wrap_std_set_sxtwl_36456a96f054a683(uintptr_t arg1);
extern uintptr_t _wrap_std_get_sxtwl_36456a96f054a683(void);
extern void _wrap_Time_Y_set_sxtwl_36456a96f054a683(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Time_Y_get_sxtwl_36456a96f054a683(uintptr_t arg1);
extern void _wrap_Time_M_set_sxtwl_36456a96f054a683(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Time_M_get_sxtwl_36456a96f054a683(uintptr_t arg1);
extern void _wrap_Time_D_set_sxtwl_36456a96f054a683(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Time_D_get_sxtwl_36456a96f054a683(uintptr_t arg1);
extern void _wrap_Time_h_set_sxtwl_36456a96f054a683(uintptr_t arg1, double arg2);
extern double _wrap_Time_h_get_sxtwl_36456a96f054a683(uintptr_t arg1);
extern void _wrap_Time_s_set_sxtwl_36456a96f054a683(uintptr_t arg1, double arg2);
extern double _wrap_Time_s_get_sxtwl_36456a96f054a683(uintptr_t arg1);
extern uintptr_t _wrap_new_Time_sxtwl_36456a96f054a683(void);
extern void _wrap_delete_Time_sxtwl_36456a96f054a683(uintptr_t arg1);
extern uintptr_t _wrap_new_GZ__SWIG_0_sxtwl_36456a96f054a683(void);
extern uintptr_t _wrap_new_GZ__SWIG_1_sxtwl_36456a96f054a683(char arg1, char arg2);
extern void _wrap_GZ_tg_set_sxtwl_36456a96f054a683(uintptr_t arg1, char arg2);
extern char _wrap_GZ_tg_get_sxtwl_36456a96f054a683(uintptr_t arg1);
extern void _wrap_GZ_dz_set_sxtwl_36456a96f054a683(uintptr_t arg1, char arg2);
extern char _wrap_GZ_dz_get_sxtwl_36456a96f054a683(uintptr_t arg1);
extern void _wrap_delete_GZ_sxtwl_36456a96f054a683(uintptr_t arg1);
extern void _wrap_Day_set_sxtwl_36456a96f054a683(uintptr_t arg1);
extern uintptr_t _wrap_Day_get_sxtwl_36456a96f054a683(void);
extern void _wrap_sxtwl_set_sxtwl_36456a96f054a683(uintptr_t arg1);
extern uintptr_t _wrap_sxtwl_get_sxtwl_36456a96f054a683(void);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_sxtwl_36456a96f054a683(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_sxtwl_36456a96f054a683(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func SetStd(arg1 Namespace) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_std_set_sxtwl_36456a96f054a683(C.uintptr_t(_swig_i_0))
}

func GetStd() (_swig_ret Namespace) {
	var swig_r Namespace
	swig_r = (Namespace)(SwigcptrNamespace(C._wrap_std_get_sxtwl_36456a96f054a683()))
	return swig_r
}

const J2000 int = 2451545
type SwigcptrTime uintptr

func (p SwigcptrTime) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrTime) SwigIsTime() {
}

func (arg1 SwigcptrTime) SetY(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Time_Y_set_sxtwl_36456a96f054a683(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrTime) GetY() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Time_Y_get_sxtwl_36456a96f054a683(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTime) SetM(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Time_M_set_sxtwl_36456a96f054a683(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrTime) GetM() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Time_M_get_sxtwl_36456a96f054a683(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTime) SetD(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Time_D_set_sxtwl_36456a96f054a683(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrTime) GetD() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Time_D_get_sxtwl_36456a96f054a683(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTime) SetH(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Time_h_set_sxtwl_36456a96f054a683(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrTime) GetH() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_Time_h_get_sxtwl_36456a96f054a683(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTime) SetS(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Time_s_set_sxtwl_36456a96f054a683(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrTime) GetS() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_Time_s_get_sxtwl_36456a96f054a683(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewTime() (_swig_ret Time) {
	var swig_r Time
	swig_r = (Time)(SwigcptrTime(C._wrap_new_Time_sxtwl_36456a96f054a683()))
	return swig_r
}

func DeleteTime(arg1 Time) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Time_sxtwl_36456a96f054a683(C.uintptr_t(_swig_i_0))
}

type Time interface {
	Swigcptr() uintptr
	SwigIsTime()
	SetY(arg2 int)
	GetY() (_swig_ret int)
	SetM(arg2 int)
	GetM() (_swig_ret int)
	SetD(arg2 int)
	GetD() (_swig_ret int)
	SetH(arg2 float64)
	GetH() (_swig_ret float64)
	SetS(arg2 float64)
	GetS() (_swig_ret float64)
}

type SwigcptrGZ uintptr

func (p SwigcptrGZ) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrGZ) SwigIsGZ() {
}

func NewGZ__SWIG_0() (_swig_ret GZ) {
	var swig_r GZ
	swig_r = (GZ)(SwigcptrGZ(C._wrap_new_GZ__SWIG_0_sxtwl_36456a96f054a683()))
	return swig_r
}

func NewGZ__SWIG_1(arg1 byte, arg2 byte) (_swig_ret GZ) {
	var swig_r GZ
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (GZ)(SwigcptrGZ(C._wrap_new_GZ__SWIG_1_sxtwl_36456a96f054a683(C.char(_swig_i_0), C.char(_swig_i_1))))
	return swig_r
}

func NewGZ(a ...interface{}) GZ {
	argc := len(a)
	if argc == 0 {
		return NewGZ__SWIG_0()
	}
	if argc == 2 {
		return NewGZ__SWIG_1(a[0].(byte), a[1].(byte))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrGZ) SetTg(arg2 byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_GZ_tg_set_sxtwl_36456a96f054a683(C.uintptr_t(_swig_i_0), C.char(_swig_i_1))
}

func (arg1 SwigcptrGZ) GetTg() (_swig_ret byte) {
	var swig_r byte
	_swig_i_0 := arg1
	swig_r = (byte)(C._wrap_GZ_tg_get_sxtwl_36456a96f054a683(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrGZ) SetDz(arg2 byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_GZ_dz_set_sxtwl_36456a96f054a683(C.uintptr_t(_swig_i_0), C.char(_swig_i_1))
}

func (arg1 SwigcptrGZ) GetDz() (_swig_ret byte) {
	var swig_r byte
	_swig_i_0 := arg1
	swig_r = (byte)(C._wrap_GZ_dz_get_sxtwl_36456a96f054a683(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func DeleteGZ(arg1 GZ) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_GZ_sxtwl_36456a96f054a683(C.uintptr_t(_swig_i_0))
}

type GZ interface {
	Swigcptr() uintptr
	SwigIsGZ()
	SetTg(arg2 byte)
	GetTg() (_swig_ret byte)
	SetDz(arg2 byte)
	GetDz() (_swig_ret byte)
}

func SetDay(arg1 Class) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_Day_set_sxtwl_36456a96f054a683(C.uintptr_t(_swig_i_0))
}

func GetDay() (_swig_ret Class) {
	var swig_r Class
	swig_r = (Class)(SwigcptrClass(C._wrap_Day_get_sxtwl_36456a96f054a683()))
	return swig_r
}

func SetSxtwl(arg1 Namespace) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sxtwl_set_sxtwl_36456a96f054a683(C.uintptr_t(_swig_i_0))
}

func GetSxtwl() (_swig_ret Namespace) {
	var swig_r Namespace
	swig_r = (Namespace)(SwigcptrNamespace(C._wrap_sxtwl_get_sxtwl_36456a96f054a683()))
	return swig_r
}


type SwigcptrNamespace uintptr
type Namespace interface {
	Swigcptr() uintptr;
}
func (p SwigcptrNamespace) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrClass uintptr
type Class interface {
	Swigcptr() uintptr;
}
func (p SwigcptrClass) Swigcptr() uintptr {
	return uintptr(p)
}

