/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.seantone.sxtwl;

public class JieQiInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected JieQiInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JieQiInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(JieQiInfo obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sxtwlJNI.delete_JieQiInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setJd(double value) {
    sxtwlJNI.JieQiInfo_jd_set(swigCPtr, this, value);
  }

  public double getJd() {
    return sxtwlJNI.JieQiInfo_jd_get(swigCPtr, this);
  }

  public void setJqIndex(short value) {
    sxtwlJNI.JieQiInfo_jqIndex_set(swigCPtr, this, value);
  }

  public short getJqIndex() {
    return sxtwlJNI.JieQiInfo_jqIndex_get(swigCPtr, this);
  }

  public JieQiInfo() {
    this(sxtwlJNI.new_JieQiInfo(), true);
  }

}
