/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


#define SWIG_VERSION 0x040101
#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1,
  SWIG_JavaIOException,
  SWIG_JavaRuntimeException,
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError,
  SWIG_JavaIllegalStateException,
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { SWIG_JavaIllegalStateException, "java/lang/IllegalStateException" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) do { if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } } while (0)


#ifdef __cplusplus
#include <utility>
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigSmartPointer {
    T *ptr;
    SwigSmartPointer(T *p) : ptr(p) { }
    ~SwigSmartPointer() { delete ptr; }
    SwigSmartPointer& operator=(SwigSmartPointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
    void reset(T *p) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = p; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigSmartPointer tmp(new T(t)); pointer = tmp; return *this; }
#if __cplusplus >=201103L
  SwigValueWrapper& operator=(T&& t) { SwigSmartPointer tmp(new T(std::move(t))); pointer = tmp; return *this; }
  operator T&&() const { return std::move(*pointer.ptr); }
#else
  operator T&() const { return *pointer.ptr; }
#endif
  T *operator&() const { return pointer.ptr; }
  static void reset(SwigValueWrapper& t, T *p) { t.pointer.reset(p); }
};

/*
 * SwigValueInit() is a generic initialisation solution as the following approach:
 * 
 *       T c_result = T();
 * 
 * doesn't compile for all types for example:
 * 
 *       unsigned int c_result = unsigned int();
 */
template <typename T> T SwigValueInit() {
  return T();
}

#if __cplusplus >=201103L
# define SWIG_STD_MOVE(OBJ) std::move(OBJ)
#else
# define SWIG_STD_MOVE(OBJ) OBJ
#endif

#endif


#include "const.h"
#include "sxtwl.h"


#include <stdint.h>		// Use the C99 official header


#include <typeinfo>
#include <stdexcept>


#include <vector>
#include <stdexcept>


#include <string>


/* Check for overflow converting to Java int (always signed 32-bit) from (unsigned variable-bit) size_t */
SWIGINTERN jint SWIG_JavaIntFromSize_t(size_t size) {
  static const jint JINT_MAX = 0x7FFFFFFF;
  return (size > (size_t)JINT_MAX) ? -1 : (jint)size;
}


SWIGINTERN jint SWIG_VectorSize(size_t size) {
  jint sz = SWIG_JavaIntFromSize_t(size);
  if (sz == -1)
    throw std::out_of_range("vector size is too large to fit into a Java int");
  return sz;
}

SWIGINTERN std::vector< double > *new_std_vector_Sl_double_Sg___SWIG_2(jint count,double const &value){
        if (count < 0)
          throw std::out_of_range("vector count must be positive");
        return new std::vector< double >(static_cast<std::vector< double >::size_type>(count), value);
      }
SWIGINTERN jint std_vector_Sl_double_Sg__doSize(std::vector< double > const *self){
        return SWIG_VectorSize(self->size());
      }
SWIGINTERN void std_vector_Sl_double_Sg__doAdd__SWIG_0(std::vector< double > *self,std::vector< double >::value_type const &x){
        self->push_back(x);
      }
SWIGINTERN void std_vector_Sl_double_Sg__doAdd__SWIG_1(std::vector< double > *self,jint index,std::vector< double >::value_type const &x){
        jint size = static_cast<jint>(self->size());
        if (0 <= index && index <= size) {
          self->insert(self->begin() + index, x);
        } else {
          throw std::out_of_range("vector index out of range");
        }
      }
SWIGINTERN std::vector< double >::value_type std_vector_Sl_double_Sg__doRemove(std::vector< double > *self,jint index){
        jint size = static_cast<jint>(self->size());
        if (0 <= index && index < size) {
          double const old_value = (*self)[index];
          self->erase(self->begin() + index);
          return old_value;
        } else {
          throw std::out_of_range("vector index out of range");
        }
      }
SWIGINTERN std::vector< double >::value_type const &std_vector_Sl_double_Sg__doGet(std::vector< double > *self,jint index){
        jint size = static_cast<jint>(self->size());
        if (index >= 0 && index < size)
          return (*self)[index];
        else
          throw std::out_of_range("vector index out of range");
      }
SWIGINTERN std::vector< double >::value_type std_vector_Sl_double_Sg__doSet(std::vector< double > *self,jint index,std::vector< double >::value_type const &val){
        jint size = static_cast<jint>(self->size());
        if (index >= 0 && index < size) {
          double const old_value = (*self)[index];
          (*self)[index] = val;
          return old_value;
        }
        else
          throw std::out_of_range("vector index out of range");
      }
SWIGINTERN void std_vector_Sl_double_Sg__doRemoveRange(std::vector< double > *self,jint fromIndex,jint toIndex){
        jint size = static_cast<jint>(self->size());
        if (0 <= fromIndex && fromIndex <= toIndex && toIndex <= size) {
          self->erase(self->begin() + fromIndex, self->begin() + toIndex);
        } else {
          throw std::out_of_range("vector index out of range");
        }
      }
SWIGINTERN std::vector< sxtwl::JieQiInfo > *new_std_vector_Sl_sxtwl_JieQiInfo_Sg___SWIG_2(jint count,sxtwl::JieQiInfo const &value){
        if (count < 0)
          throw std::out_of_range("vector count must be positive");
        return new std::vector< sxtwl::JieQiInfo >(static_cast<std::vector< sxtwl::JieQiInfo >::size_type>(count), value);
      }
SWIGINTERN jint std_vector_Sl_sxtwl_JieQiInfo_Sg__doSize(std::vector< sxtwl::JieQiInfo > const *self){
        return SWIG_VectorSize(self->size());
      }
SWIGINTERN void std_vector_Sl_sxtwl_JieQiInfo_Sg__doAdd__SWIG_0(std::vector< sxtwl::JieQiInfo > *self,std::vector< sxtwl::JieQiInfo >::value_type const &x){
        self->push_back(x);
      }
SWIGINTERN void std_vector_Sl_sxtwl_JieQiInfo_Sg__doAdd__SWIG_1(std::vector< sxtwl::JieQiInfo > *self,jint index,std::vector< sxtwl::JieQiInfo >::value_type const &x){
        jint size = static_cast<jint>(self->size());
        if (0 <= index && index <= size) {
          self->insert(self->begin() + index, x);
        } else {
          throw std::out_of_range("vector index out of range");
        }
      }
SWIGINTERN std::vector< sxtwl::JieQiInfo >::value_type std_vector_Sl_sxtwl_JieQiInfo_Sg__doRemove(std::vector< sxtwl::JieQiInfo > *self,jint index){
        jint size = static_cast<jint>(self->size());
        if (0 <= index && index < size) {
          sxtwl::JieQiInfo const old_value = (*self)[index];
          self->erase(self->begin() + index);
          return old_value;
        } else {
          throw std::out_of_range("vector index out of range");
        }
      }
SWIGINTERN std::vector< sxtwl::JieQiInfo >::value_type const &std_vector_Sl_sxtwl_JieQiInfo_Sg__doGet(std::vector< sxtwl::JieQiInfo > *self,jint index){
        jint size = static_cast<jint>(self->size());
        if (index >= 0 && index < size)
          return (*self)[index];
        else
          throw std::out_of_range("vector index out of range");
      }
SWIGINTERN std::vector< sxtwl::JieQiInfo >::value_type std_vector_Sl_sxtwl_JieQiInfo_Sg__doSet(std::vector< sxtwl::JieQiInfo > *self,jint index,std::vector< sxtwl::JieQiInfo >::value_type const &val){
        jint size = static_cast<jint>(self->size());
        if (index >= 0 && index < size) {
          sxtwl::JieQiInfo const old_value = (*self)[index];
          (*self)[index] = val;
          return old_value;
        }
        else
          throw std::out_of_range("vector index out of range");
      }
SWIGINTERN void std_vector_Sl_sxtwl_JieQiInfo_Sg__doRemoveRange(std::vector< sxtwl::JieQiInfo > *self,jint fromIndex,jint toIndex){
        jint size = static_cast<jint>(self->size());
        if (0 <= fromIndex && fromIndex <= toIndex && toIndex <= size) {
          self->erase(self->begin() + fromIndex, self->begin() + toIndex);
        } else {
          throw std::out_of_range("vector index out of range");
        }
      }

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_new_1JDList_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  std::vector< double > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (std::vector< double > *)new std::vector< double >();
  *(std::vector< double > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_new_1JDList_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::vector< double > *arg1 = 0 ;
  std::vector< double > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< double > **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::vector< double > const & is null");
    return 0;
  } 
  result = (std::vector< double > *)new std::vector< double >((std::vector< double > const &)*arg1);
  *(std::vector< double > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JDList_1capacity(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::vector< double > *arg1 = (std::vector< double > *) 0 ;
  std::vector< double >::size_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< double > **)&jarg1; 
  result = ((std::vector< double > const *)arg1)->capacity();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JDList_1reserve(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  std::vector< double > *arg1 = (std::vector< double > *) 0 ;
  std::vector< double >::size_type arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< double > **)&jarg1; 
  arg2 = (std::vector< double >::size_type)jarg2; 
  try {
    (arg1)->reserve(arg2);
  } catch(std::length_error &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return ;
  }
}


SWIGEXPORT jboolean JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JDList_1isEmpty(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  std::vector< double > *arg1 = (std::vector< double > *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< double > **)&jarg1; 
  result = (bool)((std::vector< double > const *)arg1)->empty();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JDList_1clear(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  std::vector< double > *arg1 = (std::vector< double > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< double > **)&jarg1; 
  (arg1)->clear();
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_new_1JDList_1_1SWIG_12(JNIEnv *jenv, jclass jcls, jint jarg1, jdouble jarg2) {
  jlong jresult = 0 ;
  jint arg1 ;
  double *arg2 = 0 ;
  double temp2 ;
  std::vector< double > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = jarg1; 
  temp2 = (double)jarg2; 
  arg2 = &temp2; 
  try {
    result = (std::vector< double > *)new_std_vector_Sl_double_Sg___SWIG_2(SWIG_STD_MOVE(arg1),(double const &)*arg2);
  } catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
  *(std::vector< double > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JDList_1doSize(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  std::vector< double > *arg1 = (std::vector< double > *) 0 ;
  jint result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< double > **)&jarg1; 
  try {
    result = std_vector_Sl_double_Sg__doSize((std::vector< double > const *)arg1);
  } catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
  jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JDList_1doAdd_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  std::vector< double > *arg1 = (std::vector< double > *) 0 ;
  std::vector< double >::value_type *arg2 = 0 ;
  std::vector< double >::value_type temp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< double > **)&jarg1; 
  temp2 = (std::vector< double >::value_type)jarg2; 
  arg2 = &temp2; 
  std_vector_Sl_double_Sg__doAdd__SWIG_0(arg1,(double const &)*arg2);
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JDList_1doAdd_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jdouble jarg3) {
  std::vector< double > *arg1 = (std::vector< double > *) 0 ;
  jint arg2 ;
  std::vector< double >::value_type *arg3 = 0 ;
  std::vector< double >::value_type temp3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< double > **)&jarg1; 
  arg2 = jarg2; 
  temp3 = (std::vector< double >::value_type)jarg3; 
  arg3 = &temp3; 
  try {
    std_vector_Sl_double_Sg__doAdd__SWIG_1(arg1,SWIG_STD_MOVE(arg2),(double const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return ;
  }
}


SWIGEXPORT jdouble JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JDList_1doRemove(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jdouble jresult = 0 ;
  std::vector< double > *arg1 = (std::vector< double > *) 0 ;
  jint arg2 ;
  std::vector< double >::value_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< double > **)&jarg1; 
  arg2 = jarg2; 
  try {
    result = (std::vector< double >::value_type)std_vector_Sl_double_Sg__doRemove(arg1,SWIG_STD_MOVE(arg2));
  } catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JDList_1doGet(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jdouble jresult = 0 ;
  std::vector< double > *arg1 = (std::vector< double > *) 0 ;
  jint arg2 ;
  std::vector< double >::value_type *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< double > **)&jarg1; 
  arg2 = jarg2; 
  try {
    result = (std::vector< double >::value_type *) &std_vector_Sl_double_Sg__doGet(arg1,SWIG_STD_MOVE(arg2));
  } catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
  jresult = (jdouble)*result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JDList_1doSet(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jdouble jarg3) {
  jdouble jresult = 0 ;
  std::vector< double > *arg1 = (std::vector< double > *) 0 ;
  jint arg2 ;
  std::vector< double >::value_type *arg3 = 0 ;
  std::vector< double >::value_type temp3 ;
  std::vector< double >::value_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< double > **)&jarg1; 
  arg2 = jarg2; 
  temp3 = (std::vector< double >::value_type)jarg3; 
  arg3 = &temp3; 
  try {
    result = (std::vector< double >::value_type)std_vector_Sl_double_Sg__doSet(arg1,SWIG_STD_MOVE(arg2),(double const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JDList_1doRemoveRange(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3) {
  std::vector< double > *arg1 = (std::vector< double > *) 0 ;
  jint arg2 ;
  jint arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< double > **)&jarg1; 
  arg2 = jarg2; 
  arg3 = jarg3; 
  try {
    std_vector_Sl_double_Sg__doRemoveRange(arg1,SWIG_STD_MOVE(arg2),SWIG_STD_MOVE(arg3));
  } catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_delete_1JDList(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  std::vector< double > *arg1 = (std::vector< double > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(std::vector< double > **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_new_1JQList_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  std::vector< sxtwl::JieQiInfo > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (std::vector< sxtwl::JieQiInfo > *)new std::vector< sxtwl::JieQiInfo >();
  *(std::vector< sxtwl::JieQiInfo > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_new_1JQList_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::vector< sxtwl::JieQiInfo > *arg1 = 0 ;
  std::vector< sxtwl::JieQiInfo > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< sxtwl::JieQiInfo > **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::vector< sxtwl::JieQiInfo > const & is null");
    return 0;
  } 
  result = (std::vector< sxtwl::JieQiInfo > *)new std::vector< sxtwl::JieQiInfo >((std::vector< sxtwl::JieQiInfo > const &)*arg1);
  *(std::vector< sxtwl::JieQiInfo > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JQList_1capacity(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::vector< sxtwl::JieQiInfo > *arg1 = (std::vector< sxtwl::JieQiInfo > *) 0 ;
  std::vector< sxtwl::JieQiInfo >::size_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< sxtwl::JieQiInfo > **)&jarg1; 
  result = ((std::vector< sxtwl::JieQiInfo > const *)arg1)->capacity();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JQList_1reserve(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  std::vector< sxtwl::JieQiInfo > *arg1 = (std::vector< sxtwl::JieQiInfo > *) 0 ;
  std::vector< sxtwl::JieQiInfo >::size_type arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< sxtwl::JieQiInfo > **)&jarg1; 
  arg2 = (std::vector< sxtwl::JieQiInfo >::size_type)jarg2; 
  try {
    (arg1)->reserve(arg2);
  } catch(std::length_error &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return ;
  }
}


SWIGEXPORT jboolean JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JQList_1isEmpty(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  std::vector< sxtwl::JieQiInfo > *arg1 = (std::vector< sxtwl::JieQiInfo > *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< sxtwl::JieQiInfo > **)&jarg1; 
  result = (bool)((std::vector< sxtwl::JieQiInfo > const *)arg1)->empty();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JQList_1clear(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  std::vector< sxtwl::JieQiInfo > *arg1 = (std::vector< sxtwl::JieQiInfo > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< sxtwl::JieQiInfo > **)&jarg1; 
  (arg1)->clear();
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_new_1JQList_1_1SWIG_12(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2, jobject jarg2_) {
  jlong jresult = 0 ;
  jint arg1 ;
  sxtwl::JieQiInfo *arg2 = 0 ;
  std::vector< sxtwl::JieQiInfo > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = jarg1; 
  arg2 = *(sxtwl::JieQiInfo **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "sxtwl::JieQiInfo const & is null");
    return 0;
  } 
  try {
    result = (std::vector< sxtwl::JieQiInfo > *)new_std_vector_Sl_sxtwl_JieQiInfo_Sg___SWIG_2(SWIG_STD_MOVE(arg1),(sxtwl::JieQiInfo const &)*arg2);
  } catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
  *(std::vector< sxtwl::JieQiInfo > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JQList_1doSize(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  std::vector< sxtwl::JieQiInfo > *arg1 = (std::vector< sxtwl::JieQiInfo > *) 0 ;
  jint result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< sxtwl::JieQiInfo > **)&jarg1; 
  try {
    result = std_vector_Sl_sxtwl_JieQiInfo_Sg__doSize((std::vector< sxtwl::JieQiInfo > const *)arg1);
  } catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
  jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JQList_1doAdd_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  std::vector< sxtwl::JieQiInfo > *arg1 = (std::vector< sxtwl::JieQiInfo > *) 0 ;
  std::vector< sxtwl::JieQiInfo >::value_type *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(std::vector< sxtwl::JieQiInfo > **)&jarg1; 
  arg2 = *(std::vector< sxtwl::JieQiInfo >::value_type **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::vector< sxtwl::JieQiInfo >::value_type const & is null");
    return ;
  } 
  std_vector_Sl_sxtwl_JieQiInfo_Sg__doAdd__SWIG_0(arg1,(sxtwl::JieQiInfo const &)*arg2);
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JQList_1doAdd_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jlong jarg3, jobject jarg3_) {
  std::vector< sxtwl::JieQiInfo > *arg1 = (std::vector< sxtwl::JieQiInfo > *) 0 ;
  jint arg2 ;
  std::vector< sxtwl::JieQiInfo >::value_type *arg3 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(std::vector< sxtwl::JieQiInfo > **)&jarg1; 
  arg2 = jarg2; 
  arg3 = *(std::vector< sxtwl::JieQiInfo >::value_type **)&jarg3;
  if (!arg3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::vector< sxtwl::JieQiInfo >::value_type const & is null");
    return ;
  } 
  try {
    std_vector_Sl_sxtwl_JieQiInfo_Sg__doAdd__SWIG_1(arg1,SWIG_STD_MOVE(arg2),(sxtwl::JieQiInfo const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return ;
  }
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JQList_1doRemove(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  std::vector< sxtwl::JieQiInfo > *arg1 = (std::vector< sxtwl::JieQiInfo > *) 0 ;
  jint arg2 ;
  std::vector< sxtwl::JieQiInfo >::value_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< sxtwl::JieQiInfo > **)&jarg1; 
  arg2 = jarg2; 
  try {
    result = std_vector_Sl_sxtwl_JieQiInfo_Sg__doRemove(arg1,SWIG_STD_MOVE(arg2));
  } catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
  *(std::vector< sxtwl::JieQiInfo >::value_type **)&jresult = new std::vector< sxtwl::JieQiInfo >::value_type(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JQList_1doGet(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  std::vector< sxtwl::JieQiInfo > *arg1 = (std::vector< sxtwl::JieQiInfo > *) 0 ;
  jint arg2 ;
  std::vector< sxtwl::JieQiInfo >::value_type *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< sxtwl::JieQiInfo > **)&jarg1; 
  arg2 = jarg2; 
  try {
    result = (std::vector< sxtwl::JieQiInfo >::value_type *) &std_vector_Sl_sxtwl_JieQiInfo_Sg__doGet(arg1,SWIG_STD_MOVE(arg2));
  } catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
  *(std::vector< sxtwl::JieQiInfo >::value_type **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JQList_1doSet(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jlong jarg3, jobject jarg3_) {
  jlong jresult = 0 ;
  std::vector< sxtwl::JieQiInfo > *arg1 = (std::vector< sxtwl::JieQiInfo > *) 0 ;
  jint arg2 ;
  std::vector< sxtwl::JieQiInfo >::value_type *arg3 = 0 ;
  std::vector< sxtwl::JieQiInfo >::value_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(std::vector< sxtwl::JieQiInfo > **)&jarg1; 
  arg2 = jarg2; 
  arg3 = *(std::vector< sxtwl::JieQiInfo >::value_type **)&jarg3;
  if (!arg3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::vector< sxtwl::JieQiInfo >::value_type const & is null");
    return 0;
  } 
  try {
    result = std_vector_Sl_sxtwl_JieQiInfo_Sg__doSet(arg1,SWIG_STD_MOVE(arg2),(sxtwl::JieQiInfo const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
  *(std::vector< sxtwl::JieQiInfo >::value_type **)&jresult = new std::vector< sxtwl::JieQiInfo >::value_type(result); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JQList_1doRemoveRange(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3) {
  std::vector< sxtwl::JieQiInfo > *arg1 = (std::vector< sxtwl::JieQiInfo > *) 0 ;
  jint arg2 ;
  jint arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< sxtwl::JieQiInfo > **)&jarg1; 
  arg2 = jarg2; 
  arg3 = jarg3; 
  try {
    std_vector_Sl_sxtwl_JieQiInfo_Sg__doRemoveRange(arg1,SWIG_STD_MOVE(arg2),SWIG_STD_MOVE(arg3));
  } catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_delete_1JQList(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  std::vector< sxtwl::JieQiInfo > *arg1 = (std::vector< sxtwl::JieQiInfo > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(std::vector< sxtwl::JieQiInfo > **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jint JNICALL Java_com_seantone_sxtwl_sxtwlJNI_J2000_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(2451545);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_new_1Time_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Time *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Time *)new Time();
  *(Time **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_new_1Time_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2, jint jarg3, jdouble jarg4, jdouble jarg5, jdouble jarg6) {
  jlong jresult = 0 ;
  int arg1 ;
  int arg2 ;
  int arg3 ;
  double arg4 ;
  double arg5 ;
  double arg6 ;
  Time *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (double)jarg4; 
  arg5 = (double)jarg5; 
  arg6 = (double)jarg6; 
  result = (Time *)new Time(arg1,arg2,arg3,arg4,arg5,arg6);
  *(Time **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Time_1Y_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Time *arg1 = (Time *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Time **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->Y = arg2;
}


SWIGEXPORT jint JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Time_1Y_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Time *arg1 = (Time *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Time **)&jarg1; 
  result = (int) ((arg1)->Y);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Time_1M_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Time *arg1 = (Time *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Time **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->M = arg2;
}


SWIGEXPORT jint JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Time_1M_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Time *arg1 = (Time *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Time **)&jarg1; 
  result = (int) ((arg1)->M);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Time_1D_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Time *arg1 = (Time *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Time **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->D = arg2;
}


SWIGEXPORT jint JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Time_1D_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Time *arg1 = (Time *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Time **)&jarg1; 
  result = (int) ((arg1)->D);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Time_1h_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  Time *arg1 = (Time *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Time **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->h = arg2;
}


SWIGEXPORT jdouble JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Time_1h_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  Time *arg1 = (Time *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Time **)&jarg1; 
  result = (double) ((arg1)->h);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Time_1m_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  Time *arg1 = (Time *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Time **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->m = arg2;
}


SWIGEXPORT jdouble JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Time_1m_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  Time *arg1 = (Time *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Time **)&jarg1; 
  result = (double) ((arg1)->m);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Time_1s_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  Time *arg1 = (Time *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Time **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->s = arg2;
}


SWIGEXPORT jdouble JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Time_1s_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  Time *arg1 = (Time *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Time **)&jarg1; 
  result = (double) ((arg1)->s);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Time_1getYear(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Time *arg1 = (Time *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Time **)&jarg1; 
  result = (int)(arg1)->getYear();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Time_1setYear(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Time *arg1 = (Time *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Time **)&jarg1; 
  arg2 = (int)jarg2; 
  (arg1)->setYear(arg2);
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Time_1setMonth(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Time *arg1 = (Time *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Time **)&jarg1; 
  arg2 = (int)jarg2; 
  (arg1)->setMonth(arg2);
}


SWIGEXPORT jint JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Time_1getMonth(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Time *arg1 = (Time *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Time **)&jarg1; 
  result = (int)(arg1)->getMonth();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Time_1getDay(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Time *arg1 = (Time *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Time **)&jarg1; 
  result = (int)(arg1)->getDay();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Time_1setDay(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Time *arg1 = (Time *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Time **)&jarg1; 
  arg2 = (int)jarg2; 
  (arg1)->setDay(arg2);
}


SWIGEXPORT jdouble JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Time_1getHour(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  Time *arg1 = (Time *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Time **)&jarg1; 
  result = (double)(arg1)->getHour();
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Time_1setHour(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  Time *arg1 = (Time *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Time **)&jarg1; 
  arg2 = (double)jarg2; 
  (arg1)->setHour(arg2);
}


SWIGEXPORT jdouble JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Time_1getMin(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  Time *arg1 = (Time *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Time **)&jarg1; 
  result = (double)(arg1)->getMin();
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Time_1setMour(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  Time *arg1 = (Time *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Time **)&jarg1; 
  arg2 = (double)jarg2; 
  (arg1)->setMour(arg2);
}


SWIGEXPORT jdouble JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Time_1getSec(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  Time *arg1 = (Time *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Time **)&jarg1; 
  result = (double)(arg1)->getSec();
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Time_1setSec(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  Time *arg1 = (Time *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Time **)&jarg1; 
  arg2 = (double)jarg2; 
  (arg1)->setSec(arg2);
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_delete_1Time(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Time *arg1 = (Time *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Time **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_new_1GZ_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  GZ *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (GZ *)new GZ();
  *(GZ **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_new_1GZ_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jshort jarg1, jshort jarg2) {
  jlong jresult = 0 ;
  uint8_t arg1 ;
  uint8_t arg2 ;
  GZ *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (uint8_t)jarg1; 
  arg2 = (uint8_t)jarg2; 
  result = (GZ *)new GZ(arg1,arg2);
  *(GZ **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_GZ_1tg_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  GZ *arg1 = (GZ *) 0 ;
  uint8_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(GZ **)&jarg1; 
  arg2 = (uint8_t)jarg2; 
  if (arg1) (arg1)->tg = arg2;
}


SWIGEXPORT jshort JNICALL Java_com_seantone_sxtwl_sxtwlJNI_GZ_1tg_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  GZ *arg1 = (GZ *) 0 ;
  uint8_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(GZ **)&jarg1; 
  result = (uint8_t) ((arg1)->tg);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_GZ_1dz_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  GZ *arg1 = (GZ *) 0 ;
  uint8_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(GZ **)&jarg1; 
  arg2 = (uint8_t)jarg2; 
  if (arg1) (arg1)->dz = arg2;
}


SWIGEXPORT jshort JNICALL Java_com_seantone_sxtwl_sxtwlJNI_GZ_1dz_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  GZ *arg1 = (GZ *) 0 ;
  uint8_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(GZ **)&jarg1; 
  result = (uint8_t) ((arg1)->dz);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_delete_1GZ(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  GZ *arg1 = (GZ *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GZ **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Day_1fromSolar(JNIEnv *jenv, jclass jcls, jint jarg1, jshort jarg2, jint jarg3) {
  jlong jresult = 0 ;
  int arg1 ;
  uint8_t arg2 ;
  int arg3 ;
  Day *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (uint8_t)jarg2; 
  arg3 = (int)jarg3; 
  result = (Day *)Day::fromSolar(arg1,arg2,arg3);
  *(Day **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Day_1fromLunar_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jint jarg1, jshort jarg2, jint jarg3, jboolean jarg4) {
  jlong jresult = 0 ;
  int arg1 ;
  uint8_t arg2 ;
  int arg3 ;
  bool arg4 ;
  Day *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (uint8_t)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = jarg4 ? true : false; 
  result = (Day *)Day::fromLunar(arg1,arg2,arg3,arg4);
  *(Day **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Day_1fromLunar_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jint jarg1, jshort jarg2, jint jarg3) {
  jlong jresult = 0 ;
  int arg1 ;
  uint8_t arg2 ;
  int arg3 ;
  Day *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (uint8_t)jarg2; 
  arg3 = (int)jarg3; 
  result = (Day *)Day::fromLunar(arg1,arg2,arg3);
  *(Day **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Day_1after(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  Day *arg1 = (Day *) 0 ;
  int arg2 ;
  Day *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Day **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (Day *)(arg1)->after(arg2);
  *(Day **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Day_1before(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  Day *arg1 = (Day *) 0 ;
  int arg2 ;
  Day *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Day **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (Day *)(arg1)->before(arg2);
  *(Day **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Day_1getLunarDay(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Day *arg1 = (Day *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Day **)&jarg1; 
  result = (int)(arg1)->getLunarDay();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Day_1getLunarMonth(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  Day *arg1 = (Day *) 0 ;
  uint8_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Day **)&jarg1; 
  result = (uint8_t)(arg1)->getLunarMonth();
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Day_1getLunarYear_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  jint jresult = 0 ;
  Day *arg1 = (Day *) 0 ;
  bool arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Day **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  result = (int)(arg1)->getLunarYear(arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Day_1getLunarYear_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Day *arg1 = (Day *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Day **)&jarg1; 
  result = (int)(arg1)->getLunarYear();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Day_1getYearGZ_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  jlong jresult = 0 ;
  Day *arg1 = (Day *) 0 ;
  bool arg2 ;
  GZ result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Day **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  result = (arg1)->getYearGZ(arg2);
  *(GZ **)&jresult = new GZ(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Day_1getYearGZ_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Day *arg1 = (Day *) 0 ;
  GZ result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Day **)&jarg1; 
  result = (arg1)->getYearGZ();
  *(GZ **)&jresult = new GZ(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Day_1getMonthGZ(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Day *arg1 = (Day *) 0 ;
  GZ result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Day **)&jarg1; 
  result = (arg1)->getMonthGZ();
  *(GZ **)&jresult = new GZ(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Day_1getDayGZ(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Day *arg1 = (Day *) 0 ;
  GZ result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Day **)&jarg1; 
  result = (arg1)->getDayGZ();
  *(GZ **)&jresult = new GZ(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Day_1getHourGZ_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2, jboolean jarg3) {
  jlong jresult = 0 ;
  Day *arg1 = (Day *) 0 ;
  uint8_t arg2 ;
  bool arg3 ;
  GZ result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Day **)&jarg1; 
  arg2 = (uint8_t)jarg2; 
  arg3 = jarg3 ? true : false; 
  result = (arg1)->getHourGZ(arg2,arg3);
  *(GZ **)&jresult = new GZ(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Day_1getHourGZ_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  jlong jresult = 0 ;
  Day *arg1 = (Day *) 0 ;
  uint8_t arg2 ;
  GZ result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Day **)&jarg1; 
  arg2 = (uint8_t)jarg2; 
  result = (arg1)->getHourGZ(arg2);
  *(GZ **)&jresult = new GZ(result); 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Day_1isLunarLeap(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  Day *arg1 = (Day *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Day **)&jarg1; 
  result = (bool)(arg1)->isLunarLeap();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Day_1getSolarYear(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Day *arg1 = (Day *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Day **)&jarg1; 
  result = (int)(arg1)->getSolarYear();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Day_1getSolarMonth(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  Day *arg1 = (Day *) 0 ;
  uint8_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Day **)&jarg1; 
  result = (uint8_t)(arg1)->getSolarMonth();
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Day_1getSolarDay(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Day *arg1 = (Day *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Day **)&jarg1; 
  result = (int)(arg1)->getSolarDay();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Day_1getWeek(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  Day *arg1 = (Day *) 0 ;
  uint8_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Day **)&jarg1; 
  result = (uint8_t)(arg1)->getWeek();
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Day_1getWeekIndex(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  Day *arg1 = (Day *) 0 ;
  uint8_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Day **)&jarg1; 
  result = (uint8_t)(arg1)->getWeekIndex();
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Day_1hasJieQi(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  Day *arg1 = (Day *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Day **)&jarg1; 
  result = (bool)(arg1)->hasJieQi();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Day_1getJieQi(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  Day *arg1 = (Day *) 0 ;
  uint8_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Day **)&jarg1; 
  result = (uint8_t)(arg1)->getJieQi();
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Day_1getJieQiJD(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  Day *arg1 = (Day *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Day **)&jarg1; 
  result = (double)(arg1)->getJieQiJD();
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_com_seantone_sxtwl_sxtwlJNI_Day_1getConstellation(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  Day *arg1 = (Day *) 0 ;
  uint8_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Day **)&jarg1; 
  result = (uint8_t)(arg1)->getConstellation();
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_delete_1Day(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Day *arg1 = (Day *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Day **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JieQiInfo_1jd_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  sxtwl::JieQiInfo *arg1 = (sxtwl::JieQiInfo *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(sxtwl::JieQiInfo **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->jd = arg2;
}


SWIGEXPORT jdouble JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JieQiInfo_1jd_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  sxtwl::JieQiInfo *arg1 = (sxtwl::JieQiInfo *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(sxtwl::JieQiInfo **)&jarg1; 
  result = (double) ((arg1)->jd);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JieQiInfo_1jqIndex_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  sxtwl::JieQiInfo *arg1 = (sxtwl::JieQiInfo *) 0 ;
  uint8_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(sxtwl::JieQiInfo **)&jarg1; 
  arg2 = (uint8_t)jarg2; 
  if (arg1) (arg1)->jqIndex = arg2;
}


SWIGEXPORT jshort JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JieQiInfo_1jqIndex_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  sxtwl::JieQiInfo *arg1 = (sxtwl::JieQiInfo *) 0 ;
  uint8_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(sxtwl::JieQiInfo **)&jarg1; 
  result = (uint8_t) ((arg1)->jqIndex);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_new_1JieQiInfo(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  sxtwl::JieQiInfo *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (sxtwl::JieQiInfo *)new sxtwl::JieQiInfo();
  *(sxtwl::JieQiInfo **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_seantone_sxtwl_sxtwlJNI_delete_1JieQiInfo(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  sxtwl::JieQiInfo *arg1 = (sxtwl::JieQiInfo *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(sxtwl::JieQiInfo **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_fromSolar(JNIEnv *jenv, jclass jcls, jint jarg1, jshort jarg2, jint jarg3) {
  jlong jresult = 0 ;
  int arg1 ;
  uint8_t arg2 ;
  int arg3 ;
  Day *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (uint8_t)jarg2; 
  arg3 = (int)jarg3; 
  result = (Day *)sxtwl::fromSolar(arg1,arg2,arg3);
  *(Day **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_fromLunar_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jint jarg1, jshort jarg2, jint jarg3, jboolean jarg4) {
  jlong jresult = 0 ;
  int arg1 ;
  uint8_t arg2 ;
  int arg3 ;
  bool arg4 ;
  Day *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (uint8_t)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = jarg4 ? true : false; 
  result = (Day *)sxtwl::fromLunar(arg1,arg2,arg3,arg4);
  *(Day **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_fromLunar_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jint jarg1, jshort jarg2, jint jarg3) {
  jlong jresult = 0 ;
  int arg1 ;
  uint8_t arg2 ;
  int arg3 ;
  Day *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (uint8_t)jarg2; 
  arg3 = (int)jarg3; 
  result = (Day *)sxtwl::fromLunar(arg1,arg2,arg3);
  *(Day **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_siZhu2Year(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jlong jarg3, jobject jarg3_, jlong jarg4, jobject jarg4_, jint jarg5, jint jarg6) {
  jlong jresult = 0 ;
  GZ arg1 ;
  GZ arg2 ;
  GZ arg3 ;
  GZ arg4 ;
  int arg5 ;
  int arg6 ;
  GZ *argp1 ;
  GZ *argp2 ;
  GZ *argp3 ;
  GZ *argp4 ;
  std::vector< double > result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  (void)jarg3_;
  (void)jarg4_;
  argp1 = *(GZ **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null GZ");
    return 0;
  }
  arg1 = *argp1; 
  argp2 = *(GZ **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null GZ");
    return 0;
  }
  arg2 = *argp2; 
  argp3 = *(GZ **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null GZ");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(GZ **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null GZ");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = (int)jarg5; 
  arg6 = (int)jarg6; 
  result = sxtwl::siZhu2Year(SWIG_STD_MOVE(arg1),SWIG_STD_MOVE(arg2),SWIG_STD_MOVE(arg3),SWIG_STD_MOVE(arg4),arg5,arg6);
  *(std::vector< double > **)&jresult = new std::vector< double >(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_getShiGz_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jshort jarg1, jshort jarg2, jboolean jarg3) {
  jlong jresult = 0 ;
  uint8_t arg1 ;
  uint8_t arg2 ;
  bool arg3 ;
  GZ result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (uint8_t)jarg1; 
  arg2 = (uint8_t)jarg2; 
  arg3 = jarg3 ? true : false; 
  result = sxtwl::getShiGz(arg1,arg2,arg3);
  *(GZ **)&jresult = new GZ(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_getShiGz_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jshort jarg1, jshort jarg2) {
  jlong jresult = 0 ;
  uint8_t arg1 ;
  uint8_t arg2 ;
  GZ result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (uint8_t)jarg1; 
  arg2 = (uint8_t)jarg2; 
  result = sxtwl::getShiGz(arg1,arg2);
  *(GZ **)&jresult = new GZ(result); 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_com_seantone_sxtwl_sxtwlJNI_getRunMonth(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jshort jresult = 0 ;
  int arg1 ;
  uint8_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (uint8_t)sxtwl::getRunMonth(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_com_seantone_sxtwl_sxtwlJNI_getLunarMonthNum_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jint jarg1, jshort jarg2, jboolean jarg3) {
  jshort jresult = 0 ;
  int arg1 ;
  uint8_t arg2 ;
  bool arg3 ;
  uint8_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (uint8_t)jarg2; 
  arg3 = jarg3 ? true : false; 
  result = (uint8_t)sxtwl::getLunarMonthNum(arg1,arg2,arg3);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_com_seantone_sxtwl_sxtwlJNI_getLunarMonthNum_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jint jarg1, jshort jarg2) {
  jshort jresult = 0 ;
  int arg1 ;
  uint8_t arg2 ;
  uint8_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (uint8_t)jarg2; 
  result = (uint8_t)sxtwl::getLunarMonthNum(arg1,arg2);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_JD2DD(JNIEnv *jenv, jclass jcls, jdouble jarg1) {
  jlong jresult = 0 ;
  double arg1 ;
  Time result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (double)jarg1; 
  result = sxtwl::JD2DD(arg1);
  *(Time **)&jresult = new Time(result); 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_com_seantone_sxtwl_sxtwlJNI_toJD(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  Time *arg1 = 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Time **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Time & is null");
    return 0;
  } 
  result = (double)sxtwl::toJD(*arg1);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_seantone_sxtwl_sxtwlJNI_getJieQiByYear(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  std::vector< sxtwl::JieQiInfo > result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = sxtwl::getJieQiByYear(arg1);
  *(std::vector< sxtwl::JieQiInfo > **)&jresult = new std::vector< sxtwl::JieQiInfo >(result); 
  return jresult;
}


#ifdef __cplusplus
}
#endif

