/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.seantone.sxtwl;

public class sxtwl implements sxtwlConstants {
  public static Day fromSolar(int year, short month, int day) {
    long cPtr = sxtwlJNI.fromSolar(year, month, day);
    return (cPtr == 0) ? null : new Day(cPtr, false);
  }

  public static Day fromLunar(int year, short month, int day, boolean isRun) {
    long cPtr = sxtwlJNI.fromLunar__SWIG_0(year, month, day, isRun);
    return (cPtr == 0) ? null : new Day(cPtr, false);
  }

  public static Day fromLunar(int year, short month, int day) {
    long cPtr = sxtwlJNI.fromLunar__SWIG_1(year, month, day);
    return (cPtr == 0) ? null : new Day(cPtr, false);
  }

  public static JDList siZhu2Year(GZ year, GZ yue, GZ ri, GZ shi, int fromYear, int toYear) {
    return new JDList(sxtwlJNI.siZhu2Year(GZ.getCPtr(year), year, GZ.getCPtr(yue), yue, GZ.getCPtr(ri), ri, GZ.getCPtr(shi), shi, fromYear, toYear), true);
  }

  public static GZ getShiGz(short dayTg, short hour, boolean isZaoWanZiShi) {
    return new GZ(sxtwlJNI.getShiGz__SWIG_0(dayTg, hour, isZaoWanZiShi), true);
  }

  public static GZ getShiGz(short dayTg, short hour) {
    return new GZ(sxtwlJNI.getShiGz__SWIG_1(dayTg, hour), true);
  }

  public static short getRunMonth(int By) {
    return sxtwlJNI.getRunMonth(By);
  }

  public static short getLunarMonthNum(int By, short month, boolean isRun) {
    return sxtwlJNI.getLunarMonthNum__SWIG_0(By, month, isRun);
  }

  public static short getLunarMonthNum(int By, short month) {
    return sxtwlJNI.getLunarMonthNum__SWIG_1(By, month);
  }

  public static Time JD2DD(double jd) {
    return new Time(sxtwlJNI.JD2DD(jd), true);
  }

  public static double toJD(Time time) {
    return sxtwlJNI.toJD(Time.getCPtr(time), time);
  }

  public static JQList getJieQiByYear(int year) {
    return new JQList(sxtwlJNI.getJieQiByYear(year), true);
  }

}
