/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.seantone.sxtwl;

public class Time {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Time(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Time obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Time obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sxtwlJNI.delete_Time(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Time() {
    this(sxtwlJNI.new_Time__SWIG_0(), true);
  }

  public Time(int year, int month, int day, double hour, double min, double sec) {
    this(sxtwlJNI.new_Time__SWIG_1(year, month, day, hour, min, sec), true);
  }

  public void setY(int value) {
    sxtwlJNI.Time_Y_set(swigCPtr, this, value);
  }

  public int getY() {
    return sxtwlJNI.Time_Y_get(swigCPtr, this);
  }

  public void setM(int value) {
    sxtwlJNI.Time_M_set(swigCPtr, this, value);
  }

  public int getM() {
    return sxtwlJNI.Time_M_get(swigCPtr, this);
  }

  public void setD(int value) {
    sxtwlJNI.Time_D_set(swigCPtr, this, value);
  }

  public int getD() {
    return sxtwlJNI.Time_D_get(swigCPtr, this);
  }

  public void setH(double value) {
    sxtwlJNI.Time_h_set(swigCPtr, this, value);
  }

  public double getH() {
    return sxtwlJNI.Time_h_get(swigCPtr, this);
  }

  public void setM(double value) {
    sxtwlJNI.Time_m_set(swigCPtr, this, value);
  }

  public double getM() {
    return sxtwlJNI.Time_m_get(swigCPtr, this);
  }

  public void setS(double value) {
    sxtwlJNI.Time_s_set(swigCPtr, this, value);
  }

  public double getS() {
    return sxtwlJNI.Time_s_get(swigCPtr, this);
  }

  public int getYear() {
    return sxtwlJNI.Time_getYear(swigCPtr, this);
  }

  public void setYear(int year) {
    sxtwlJNI.Time_setYear(swigCPtr, this, year);
  }

  public void setMonth(int month) {
    sxtwlJNI.Time_setMonth(swigCPtr, this, month);
  }

  public int getMonth() {
    return sxtwlJNI.Time_getMonth(swigCPtr, this);
  }

  public int getDay() {
    return sxtwlJNI.Time_getDay(swigCPtr, this);
  }

  public void setDay(int day) {
    sxtwlJNI.Time_setDay(swigCPtr, this, day);
  }

  public double getHour() {
    return sxtwlJNI.Time_getHour(swigCPtr, this);
  }

  public void setHour(double hour) {
    sxtwlJNI.Time_setHour(swigCPtr, this, hour);
  }

  public double getMin() {
    return sxtwlJNI.Time_getMin(swigCPtr, this);
  }

  public void setMour(double min) {
    sxtwlJNI.Time_setMour(swigCPtr, this, min);
  }

  public double getSec() {
    return sxtwlJNI.Time_getSec(swigCPtr, this);
  }

  public void setSec(double sec) {
    sxtwlJNI.Time_setSec(swigCPtr, this, sec);
  }

}
