/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.seantone.sxtwl;

public class Time {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Time(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Time obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sxtwlJNI.delete_Time(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Time() {
    this(sxtwlJNI.new_Time__SWIG_0(), true);
  }

  public Time(int year, int month, int day, double hour, double min, double sec) {
    this(sxtwlJNI.new_Time__SWIG_1(year, month, day, hour, min, sec), true);
  }

  public void setYear(int value) {
    sxtwlJNI.Time_year_set(swigCPtr, this, value);
  }

  public int getYear() {
    return sxtwlJNI.Time_year_get(swigCPtr, this);
  }

  public void setMonth(int value) {
    sxtwlJNI.Time_month_set(swigCPtr, this, value);
  }

  public int getMonth() {
    return sxtwlJNI.Time_month_get(swigCPtr, this);
  }

  public void setDay(int value) {
    sxtwlJNI.Time_day_set(swigCPtr, this, value);
  }

  public int getDay() {
    return sxtwlJNI.Time_day_get(swigCPtr, this);
  }

  public void setHour(double value) {
    sxtwlJNI.Time_hour_set(swigCPtr, this, value);
  }

  public double getHour() {
    return sxtwlJNI.Time_hour_get(swigCPtr, this);
  }

  public void setMin(double value) {
    sxtwlJNI.Time_min_set(swigCPtr, this, value);
  }

  public double getMin() {
    return sxtwlJNI.Time_min_get(swigCPtr, this);
  }

  public void setSec(double value) {
    sxtwlJNI.Time_sec_set(swigCPtr, this, value);
  }

  public double getSec() {
    return sxtwlJNI.Time_sec_get(swigCPtr, this);
  }

}
