//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Time : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Time(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Time obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Time() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          sxtwlPINVOKE.delete_Time(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Time() : this(sxtwlPINVOKE.new_Time__SWIG_0(), true) {
  }

  public Time(int year, int month, int day, double hour, double min, double sec) : this(sxtwlPINVOKE.new_Time__SWIG_1(year, month, day, hour, min, sec), true) {
  }

  public int year {
    set {
      sxtwlPINVOKE.Time_year_set(swigCPtr, value);
    } 
    get {
      int ret = sxtwlPINVOKE.Time_year_get(swigCPtr);
      return ret;
    } 
  }

  public int month {
    set {
      sxtwlPINVOKE.Time_month_set(swigCPtr, value);
    } 
    get {
      int ret = sxtwlPINVOKE.Time_month_get(swigCPtr);
      return ret;
    } 
  }

  public int day {
    set {
      sxtwlPINVOKE.Time_day_set(swigCPtr, value);
    } 
    get {
      int ret = sxtwlPINVOKE.Time_day_get(swigCPtr);
      return ret;
    } 
  }

  public double hour {
    set {
      sxtwlPINVOKE.Time_hour_set(swigCPtr, value);
    } 
    get {
      double ret = sxtwlPINVOKE.Time_hour_get(swigCPtr);
      return ret;
    } 
  }

  public double min {
    set {
      sxtwlPINVOKE.Time_min_set(swigCPtr, value);
    } 
    get {
      double ret = sxtwlPINVOKE.Time_min_get(swigCPtr);
      return ret;
    } 
  }

  public double sec {
    set {
      sxtwlPINVOKE.Time_sec_set(swigCPtr, value);
    } 
    get {
      double ret = sxtwlPINVOKE.Time_sec_get(swigCPtr);
      return ret;
    } 
  }

}
