//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Time : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Time(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Time obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Time() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          sxtwlPINVOKE.delete_Time(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int Y {
    set {
      sxtwlPINVOKE.Time_Y_set(swigCPtr, value);
    } 
    get {
      int ret = sxtwlPINVOKE.Time_Y_get(swigCPtr);
      return ret;
    } 
  }

  public int M {
    set {
      sxtwlPINVOKE.Time_M_set(swigCPtr, value);
    } 
    get {
      int ret = sxtwlPINVOKE.Time_M_get(swigCPtr);
      return ret;
    } 
  }

  public int D {
    set {
      sxtwlPINVOKE.Time_D_set(swigCPtr, value);
    } 
    get {
      int ret = sxtwlPINVOKE.Time_D_get(swigCPtr);
      return ret;
    } 
  }

  public double h {
    set {
      sxtwlPINVOKE.Time_h_set(swigCPtr, value);
    } 
    get {
      double ret = sxtwlPINVOKE.Time_h_get(swigCPtr);
      return ret;
    } 
  }

  public double m {
    set {
      sxtwlPINVOKE.Time_m_set(swigCPtr, value);
    } 
    get {
      double ret = sxtwlPINVOKE.Time_m_get(swigCPtr);
      return ret;
    } 
  }

  public double s {
    set {
      sxtwlPINVOKE.Time_s_set(swigCPtr, value);
    } 
    get {
      double ret = sxtwlPINVOKE.Time_s_get(swigCPtr);
      return ret;
    } 
  }

  public Time() : this(sxtwlPINVOKE.new_Time(), true) {
  }

}
